name: Trigger auto deployment for subcontractor-management

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/subcontractor-management-AutoDeployTrigger-16202278-a639-4ea8-8a8c-d25da35ee953.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SUBCONTRACTORMANAGEMENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SUBCONTRACTORMANAGEMENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBCONTRACTORMANAGEMENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: coaltarcheckeracr.azurecr.io
          registryUsername: ${{ secrets.SUBCONTRACTORMANAGEMENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SUBCONTRACTORMANAGEMENT_REGISTRY_PASSWORD }}
          containerAppName: subcontractor-management
          resourceGroup: hpp-static-webapps-rg
          imageToBuild: coaltarcheckeracr.azurecr.io/subcontractor-management:${{ github.sha }}
